name: Publish package to NPM

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.15
      - run: bun install --frozen-lockfile
      - run: bun run build
      - run: bun run test

  publish-to-npm:
    needs: build
    name: publish-to-npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.15
          registry-url: 'https://registry.npmjs.org'
      - run: bun install --frozen-lockfile
      - run: bun run build
      - run: bun publish --access public --ignore-scripts
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}